language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install flake8
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install -g eclint

script:
  - flake8 .
  - eclint check *.py sites/*.py
